// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvaoM56tWWSrdI7fuDDMxiduT3fA_ATJ4',
    appId: '1:257429690717:web:070df68a3d99e1197f70b4',
    messagingSenderId: '257429690717',
    projectId: 'lab-sample-435d1',
    authDomain: 'lab-sample-435d1.firebaseapp.com',
    storageBucket: 'lab-sample-435d1.appspot.com',
    measurementId: 'G-FQDR2XR2T2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8wr-OzCzyLgJZFO9PZMSDAEu4xxSdVrY',
    appId: '1:257429690717:android:c176018b1867807c7f70b4',
    messagingSenderId: '257429690717',
    projectId: 'lab-sample-435d1',
    storageBucket: 'lab-sample-435d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmjJ205qed3V9kYH7XMchHJxSW0agdHxo',
    appId: '1:257429690717:ios:9da712c688d85c8e7f70b4',
    messagingSenderId: '257429690717',
    projectId: 'lab-sample-435d1',
    storageBucket: 'lab-sample-435d1.appspot.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmjJ205qed3V9kYH7XMchHJxSW0agdHxo',
    appId: '1:257429690717:ios:9da712c688d85c8e7f70b4',
    messagingSenderId: '257429690717',
    projectId: 'lab-sample-435d1',
    storageBucket: 'lab-sample-435d1.appspot.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvaoM56tWWSrdI7fuDDMxiduT3fA_ATJ4',
    appId: '1:257429690717:web:4bd31656a23f0ac87f70b4',
    messagingSenderId: '257429690717',
    projectId: 'lab-sample-435d1',
    authDomain: 'lab-sample-435d1.firebaseapp.com',
    storageBucket: 'lab-sample-435d1.appspot.com',
    measurementId: 'G-0QDY0TC25V',
  );
}
